In [1]:
import pandas as pd ##Importing Pandas
import numpy as np ##Importing Numpy
import warnings ##importing warnings
warnings.filterwarnings("ignore") ##Initiating to ignore the warnings

In [2]:
df = pd.read_csv("dirty_cafe_sales.csv") ##Reading the csv into a DF

In [3]:
print(df.shape) ##Getting the shape
df.head() ##Looking at the data

(10000, 8)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [5]:
df.isna().sum().sort_values() ##Checking the null values in data

Transaction ID         0
Quantity             138
Transaction Date     159
Total Spent          173
Price Per Unit       179
Item                 333
Payment Method      2579
Location            3265
dtype: int64

In [6]:
df.replace({'ERROR':np.nan,'UNKNOWN':np.nan}) ##Replacing the wrong values to nan(imported NUMPY for this purpose)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,NaN,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,NaN,NaN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,NaN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [7]:
df.replace({'ERROR':np.nan,'UNKNOWN':np.nan},inplace=True) ##Replacing the wrong values to nan(imported NUMPY for this purpose), missed to mention inplace in above step

In [8]:
df.isna().sum().sort_values() ##The actual count of nan's in the data

Transaction ID         0
Transaction Date     460
Quantity             479
Total Spent          502
Price Per Unit       533
Item                 969
Payment Method      3178
Location            3961
dtype: int64

In [9]:
twofield = df[['Item','Price Per Unit']] ##Creating a df with Item and Price

In [10]:
twofield.shape ##Checking the shape

(10000, 2)

In [11]:
twofield.drop_duplicates(inplace=True) ##Dropping the duplicates

In [12]:
twofield.dropna(inplace=True) ##Dropping the null records

In [13]:
twofield.shape ##checking the shape after the drop of nulls and duplicates

(8, 2)

In [14]:
df1 = pd.merge(df,twofield,on='Item',how='left') ##Joining the twofield dataframe to the df and creating a new df: df1

In [15]:
df1.shape ##checking the shape

(10000, 9)

In [16]:
df1.head() ##to look how the df looks

,Transaction ID,Item,Quantity,Price Per Unit_x,Total Spent,Payment Method,Location,Transaction Date,Price Per Unit_y
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08,2.0
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16,3.0
2,TXN_4271903,Cookie,4,1.0,NaN,Credit Card,In-store,2023-07-19,1.0
3,TXN_7034554,Salad,2,5.0,10.0,NaN,NaN,2023-04-27,5.0
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11,2.0

In [17]:
df1.isna().sum().sort_values()  ##To see the nulls after adding the new Price column

Transaction ID         0
Transaction Date     460
Quantity             479
Total Spent          502
Price Per Unit_x     533
Item                 969
Price Per Unit_y     969
Payment Method      3178
Location            3961
dtype: int64

In [18]:
df1['Price Per Unit_y'] = df1['Price Per Unit_y'].fillna(df1['Price Per Unit_x']) ##Filling the nulls in new column

In [19]:
df1.isna().sum().sort_values() ##checking the nulls after fillna

Transaction ID         0
Price Per Unit_y      54
Transaction Date     460
Quantity             479
Total Spent          502
Price Per Unit_x     533
Item                 969
Payment Method      3178
Location            3961
dtype: int64

In [20]:
df1.drop(['Price Per Unit_x'],axis='columns',inplace=True) ##Dropping the actual column

In [21]:
df1.rename(columns={'Price Per Unit_y':'Price Per Unit'},inplace=True) ##Renaming the new column

In [22]:
df1.shape ##checking the shape

(10000, 8)

In [23]:
df1.head() ##Seeing the df

,Transaction ID,Item,Quantity,Total Spent,Payment Method,Location,Transaction Date,Price Per Unit
0,TXN_1961373,Coffee,2,4.0,Credit Card,Takeaway,2023-09-08,2.0
1,TXN_4977031,Cake,4,12.0,Cash,In-store,2023-05-16,3.0
2,TXN_4271903,Cookie,4,NaN,Credit Card,In-store,2023-07-19,1.0
3,TXN_7034554,Salad,2,10.0,NaN,NaN,2023-04-27,5.0
4,TXN_3160411,Coffee,2,4.0,Digital Wallet,In-store,2023-06-11,2.0

In [25]:
threefield = df1[df1['Price Per Unit'].isin([np.nan])][['Transaction ID','Quantity','Total Spent']] ##Creating a df with T ID, Quant, T Spent records where the Price column is null

In [26]:
print(threefield.shape) ##Checking the shape and seeing the df
threefield.head()

(54, 3)

    Transaction ID Quantity Total Spent
118    TXN_4633784        5        15.0
151    TXN_4031509        4        16.0
289    TXN_3495950        4         6.0
334    TXN_2523298        4         6.0
550    TXN_4186681        4         6.0

In [27]:
threefield.dropna(inplace=True) ##Dropping the null values from the df

In [28]:
threefield.shape ##Checking the shape after dropna

(48, 3)

In [29]:
threefield['Quantity'] = threefield['Quantity'].astype(float) ##Changing the dtypes for the Quantity, Total Spent field
threefield['Total Spent'] = threefield['Total Spent'].astype(float)

In [30]:
threefield['PPU'] = threefield['Total Spent']/threefield['Quantity'] ##creating a new price column by calculating the Quantity and Total Spent

In [31]:
print(threefield.shape) ##Checking the shape and looking at the data
threefield.head()

(48, 4)

    Transaction ID  Quantity  Total Spent  PPU
118    TXN_4633784       5.0         15.0  3.0
151    TXN_4031509       4.0         16.0  4.0
289    TXN_3495950       4.0          6.0  1.5
334    TXN_2523298       4.0          6.0  1.5
550    TXN_4186681       4.0          6.0  1.5

In [32]:
threefield.drop(['Quantity','Total Spent'],axis='columns',inplace=True) ##Dropping the field that are not required

In [33]:
threefield.head() ##looking at the df sturc

    Transaction ID  PPU
118    TXN_4633784  3.0
151    TXN_4031509  4.0
289    TXN_3495950  1.5
334    TXN_2523298  1.5
550    TXN_4186681  1.5

In [34]:
df1 = pd.merge(df1,threefield,on='Transaction ID',how='left') ##Joining the price field to the main df1 based on T ID

In [35]:
df1.isna().sum().sort_values() ##Now checking the nulls

Transaction ID         0
Price Per Unit        54
Transaction Date     460
Quantity             479
Total Spent          502
Item                 969
Payment Method      3178
Location            3961
PPU                 9952
dtype: int64

In [36]:
df1['PPU'] = df1['PPU'].fillna(df1['Price Per Unit']) ##Filling the nulls in new column with values from Price Per Unit

In [37]:
df1.isna().sum().sort_values() ##checking the nulls after the fillna

Transaction ID         0
PPU                    6
Price Per Unit        54
Transaction Date     460
Quantity             479
Total Spent          502
Item                 969
Payment Method      3178
Location            3961
dtype: int64

In [38]:
df1.drop(['Price Per Unit'],axis='columns',inplace=True) ##Dropping the actual field

In [39]:
df1.rename(columns={'PPU':'Price Per Unit'},inplace=True) ##renaming the new filed with less nulls

In [40]:
print(df1.shape)
df1.isna().sum().sort_values() ##checking the shape and looking at the count of nulls in df

(10000, 8)

Transaction ID         0
Price Per Unit         6
Transaction Date     460
Quantity             479
Total Spent          502
Item                 969
Payment Method      3178
Location            3961
dtype: int64

In [41]:
df1.dtypes ##checking the dtypes of the df1

Transaction ID      object
Item                object
Quantity            object
Total Spent         object
Payment Method      object
Location            object
Transaction Date    object
Price Per Unit      object
dtype: object

In [42]:
df1['Price Per Unit'] = df1['Price Per Unit'].astype(float)
df1['Quantity'] = df1['Quantity'].astype(float)
df1['Total Spent'] = df1['Total Spent'].astype(float) ##Converting all the numerical field dtype to be float

In [43]:
df1.dtypes ##checking dtypes after the change

Transaction ID       object
Item                 object
Quantity            float64
Total Spent         float64
Payment Method       object
Location             object
Transaction Date     object
Price Per Unit      float64
dtype: object

In [44]:
df1['QNew'] = df1['Quantity'].fillna(df1['Total Spent']/df1['Price Per Unit'])
df1['TSNew'] = df1['Total Spent'].fillna(df1['QNew']*df1['Price Per Unit']) ##Creating new Quantity and Total Spent fields based on logics

In [45]:
print(df1.shape)
df1.head() ##Checking the shape and looking the struc of df1

(10000, 10)

,Transaction ID,Item,Quantity,Total Spent,Payment Method,Location,Transaction Date,Price Per Unit,QNew,TSNew
0,TXN_1961373,Coffee,2.0,4.0,Credit Card,Takeaway,2023-09-08,2.0,2.0,4.0
1,TXN_4977031,Cake,4.0,12.0,Cash,In-store,2023-05-16,3.0,4.0,12.0
2,TXN_4271903,Cookie,4.0,NaN,Credit Card,In-store,2023-07-19,1.0,4.0,4.0
3,TXN_7034554,Salad,2.0,10.0,NaN,NaN,2023-04-27,5.0,2.0,10.0
4,TXN_3160411,Coffee,2.0,4.0,Digital Wallet,In-store,2023-06-11,2.0,2.0,4.0

In [46]:
df1.isna().sum().sort_values() ##Now looking at the nulls after the new Quanitty and Total Spet fields

Transaction ID         0
Price Per Unit         6
QNew                  23
TSNew                 23
Transaction Date     460
Quantity             479
Total Spent          502
Item                 969
Payment Method      3178
Location            3961
dtype: int64

In [48]:
df1.drop(['Total Spent','Quantity'],axis='columns',inplace=True) ##Dropping the original field which has more nulls

In [49]:
df1.head()

,Transaction ID,Item,Payment Method,Location,Transaction Date,Price Per Unit,QNew,TSNew
0,TXN_1961373,Coffee,Credit Card,Takeaway,2023-09-08,2.0,2.0,4.0
1,TXN_4977031,Cake,Cash,In-store,2023-05-16,3.0,4.0,12.0
2,TXN_4271903,Cookie,Credit Card,In-store,2023-07-19,1.0,4.0,4.0
3,TXN_7034554,Salad,NaN,NaN,2023-04-27,5.0,2.0,10.0
4,TXN_3160411,Coffee,Digital Wallet,In-store,2023-06-11,2.0,2.0,4.0

In [52]:
df1.rename(columns={'QNew':'Quantity'.{'TSNew':'Total Spent'}},inplace=True) ##Renaming the new columns to actual names

In [53]:
df1.head() ##Looking at the df1 after the change

,Transaction ID,Item,Payment Method,Location,Transaction Date,Price Per Unit,Quantity,Total Spent
0,TXN_1961373,Coffee,Credit Card,Takeaway,2023-09-08,2.0,2.0,4.0
1,TXN_4977031,Cake,Cash,In-store,2023-05-16,3.0,4.0,12.0
2,TXN_4271903,Cookie,Credit Card,In-store,2023-07-19,1.0,4.0,4.0
3,TXN_7034554,Salad,NaN,NaN,2023-04-27,5.0,2.0,10.0
4,TXN_3160411,Coffee,Digital Wallet,In-store,2023-06-11,2.0,2.0,4.0

In [54]:
df1.median() ##In the numerical field we're still having nulls, so finding the median to fill them

Price Per Unit    3.0
Quantity          3.0
Total Spent       8.0
dtype: float64

In [55]:
df1['Price Per Unit'] = df1['Price Per Unit'].fillna(df1['Price Per Unit'].median()) ##Finding the median of Price and filling in na's
df1['Quantity'] = df1['Quantity'].fillna(df1['Quantity'].median()) ##Finding the median of Quantity and filling the na's
df1['Total Spent'] = df1['Total Spent'].fillna(9) ##Filling the na's in Total Spent with 9

In [56]:
df1.isna().sum().sort_values() ##checking the count of na's after the above three steps

Transaction ID         0
Price Per Unit         0
Quantity               0
Total Spent            0
Transaction Date     460
Item                 969
Payment Method      3178
Location            3961
dtype: int64

In [57]:
GroupByPpu = df1.groupby(df1['Price Per Unit']) ##creating a group by object

In [58]:
df1['ItemNew'] = GroupByPpu.Item.transform(lambda x: x.fillna(x.mode()[0])) ##Filling the na's in Item field with mode of each Price

In [59]:
print(df1.shape)
print(df1.head())
df1.isna().sum().sort_values() ##Checking the shape, looking at the data and seeing the na's

(10000, 9)
  Transaction ID    Item  Payment Method  Location Transaction Date  \
0    TXN_1961373  Coffee     Credit Card  Takeaway       2023-09-08
1    TXN_4977031    Cake            Cash  In-store       2023-05-16
2    TXN_4271903  Cookie     Credit Card  In-store       2023-07-19
3    TXN_7034554   Salad             NaN       NaN       2023-04-27
4    TXN_3160411  Coffee  Digital Wallet  In-store       2023-06-11

   Price Per Unit  Quantity  Total Spent ItemNew
0             2.0       2.0          4.0  Coffee
1             3.0       4.0         12.0    Cake
2             1.0       4.0          4.0  Cookie
3             5.0       2.0         10.0   Salad
4             2.0       2.0          4.0  Coffee

Transaction ID         0
Price Per Unit         0
Quantity               0
Total Spent            0
ItemNew                0
Transaction Date     460
Item                 969
Payment Method      3178
Location            3961
dtype: int64

In [60]:
df1.drop(['Item'],axis='columns',inplace=True) ##Dropping the actual Item field

In [61]:
df1.rename(columns={'ItemNew':'Item'},inplace=True) ##Renaming the new field

In [62]:
print(df1.shape)

(10000, 8)

In [63]:
df1 = df1.sort_values(by='Transaction ID') ##Sorting the data by T ID

In [64]:
df1.head() ##Checking the df after the sort

,Transaction ID,Payment Method,Location,Transaction Date,Price Per Unit,Quantity,Total Spent,Item
2987,TXN_1000555,Credit Card,In-store,2023-10-19,1.5,1.0,1.5,Tea
115,TXN_1001832,Cash,Takeaway,NaN,5.0,2.0,10.0,Salad
418,TXN_1002457,Digital Wallet,Takeaway,2023-09-29,1.0,5.0,5.0,Cookie
3417,TXN_1003246,NaN,NaN,2023-02-15,3.0,2.0,6.0,Juice
4366,TXN_1004184,Credit Card,In-store,2023-05-18,4.0,1.0,4.0,Smoothie

In [65]:
df1['TDNew'] = df1['Transaction Date'].fillna(method='ffill') ##Filling the nulls in Date as per the previous date ordered by T ID

In [66]:
df1.head() ##checking the data struc to see the change happened

,Transaction ID,Payment Method,Location,Transaction Date,Price Per Unit,Quantity,Total Spent,Item,TDNew
2987,TXN_1000555,Credit Card,In-store,2023-10-19,1.5,1.0,1.5,Tea,2023-10-19
115,TXN_1001832,Cash,Takeaway,NaN,5.0,2.0,10.0,Salad,2023-10-19
418,TXN_1002457,Digital Wallet,Takeaway,2023-09-29,1.0,5.0,5.0,Cookie,2023-09-29
3417,TXN_1003246,NaN,NaN,2023-02-15,3.0,2.0,6.0,Juice,2023-02-15
4366,TXN_1004184,Credit Card,In-store,2023-05-18,4.0,1.0,4.0,Smoothie,2023-05-18

In [67]:
df1.drop(['Transaction Date'],axis='columns',inplace=True) ##Dropping the actual date field
df1.rename(columns={'TDNew':'Transaction Date'},inplace=True) ##Renaming the new date field to actual name

In [68]:
df1.head() ##checking the data after the change

,Transaction ID,Payment Method,Location,Price Per Unit,Quantity,Total Spent,Item,Transaction Date
2987,TXN_1000555,Credit Card,In-store,1.5,1.0,1.5,Tea,2023-10-19
115,TXN_1001832,Cash,Takeaway,5.0,2.0,10.0,Salad,2023-10-19
418,TXN_1002457,Digital Wallet,Takeaway,1.0,5.0,5.0,Cookie,2023-09-29
3417,TXN_1003246,NaN,NaN,3.0,2.0,6.0,Juice,2023-02-15
4366,TXN_1004184,Credit Card,In-store,4.0,1.0,4.0,Smoothie,2023-05-18

In [69]:
df1.isna().sum().sort_values() #checking for the nulls values

Transaction ID         0
Price Per Unit         0
Quantity               0
Total Spent            0
Item                   0
Transaction Date       0
Payment Method      3178
Location            3961
dtype: int64

In [70]:
GroupByItem = df1.groupby(df1['Item']) ##creating a groupby object based on the Item

In [75]:
df1['PMNew'] = GroupByItem['Payment Method'].transform(lambda x: x.fillna(x.mode()[0])) ##Fillng the na's in Pay Method based on the mode of each Item
df1['LNew'] = GroupByItem['Location'].transform(lambda x: x.fillna(x.mode()[0]))##Fillng the na's in Location based on the mode of each Item

In [76]:
df1.head() ##Looking at the data after the change

,Transaction ID,Payment Method,Location,Price Per Unit,Quantity,Total Spent,Item,Transaction Date,PMNew,LNew
2987,TXN_1000555,Credit Card,In-store,1.5,1.0,1.5,Tea,2023-10-19,Credit Card,In-store
115,TXN_1001832,Cash,Takeaway,5.0,2.0,10.0,Salad,2023-10-19,Cash,Takeaway
418,TXN_1002457,Digital Wallet,Takeaway,1.0,5.0,5.0,Cookie,2023-09-29,Digital Wallet,Takeaway
3417,TXN_1003246,NaN,NaN,3.0,2.0,6.0,Juice,2023-02-15,Digital Wallet,In-store
4366,TXN_1004184,Credit Card,In-store,4.0,1.0,4.0,Smoothie,2023-05-18,Credit Card,In-store

In [77]:
df1.isna().sum() ##checking the nuls after the fillna

Transaction ID         0
Payment Method      3178
Location            3961
Price Per Unit         0
Quantity               0
Total Spent            0
Item                   0
Transaction Date       0
PMNew                  0
LNew                   0
dtype: int64

In [79]:
df1.drop(['Payment Method','Location'],axis='columns',inplace=True) ##Dropping the actual columns which have nulls

In [80]:
df1.rename(columns={'PMNew':'Payment Method','LNew':'Location'},inplace=True) ##Renaming the new fields

In [81]:
df1.head() ##checking the data

,Transaction ID,Price Per Unit,Quantity,Total Spent,Item,Transaction Date,Payment Method,Location
2987,TXN_1000555,1.5,1.0,1.5,Tea,2023-10-19,Credit Card,In-store
115,TXN_1001832,5.0,2.0,10.0,Salad,2023-10-19,Cash,Takeaway
418,TXN_1002457,1.0,5.0,5.0,Cookie,2023-09-29,Digital Wallet,Takeaway
3417,TXN_1003246,3.0,2.0,6.0,Juice,2023-02-15,Digital Wallet,In-store
4366,TXN_1004184,4.0,1.0,4.0,Smoothie,2023-05-18,Credit Card,In-store

In [82]:
df1.isna().sum() ##Checking the nulls in df

Transaction ID      0
Price Per Unit      0
Quantity            0
Total Spent         0
Item                0
Transaction Date    0
Payment Method      0
Location            0
dtype: int64

In [83]:
df1 = df1.reset_index(drop=True) ##Resertting the index as we have changed the sort earlier

In [84]:
df1 ##checking the df

,Transaction ID,Price Per Unit,Quantity,Total Spent,Item,Transaction Date,Payment Method,Location
0,TXN_1000555,1.5,1.0,1.5,Tea,2023-10-19,Credit Card,In-store
1,TXN_1001832,5.0,2.0,10.0,Salad,2023-10-19,Cash,Takeaway
2,TXN_1002457,1.0,5.0,5.0,Cookie,2023-09-29,Digital Wallet,Takeaway
3,TXN_1003246,3.0,2.0,6.0,Juice,2023-02-15,Digital Wallet,In-store
4,TXN_1004184,4.0,1.0,4.0,Smoothie,2023-05-18,Credit Card,In-store
...,...,...,...,...,...,...,...,...
9995,TXN_9996968,4.0,1.0,4.0,Sandwich,2023-10-14,Cash,In-store
9996,TXN_9997263,1.0,2.0,2.0,Cookie,2023-03-05,Digital Wallet,Takeaway
9997,TXN_9997620,1.0,2.0,2.0,Cookie,2023-12-11,Cash,Takeaway
9998,TXN_9999113,3.0,4.0,12.0,Juice,2023-05-27,Cash,Takeaway
9999,TXN_9999124,3.0,2.0,6.0,Juice,2023-05-27,Digital Wallet,Takeaway

In [85]:
df1.to_csv('CleanedCafeSalesData.csv') ##Saving the df to a csv